### ISSUE TITLE
bond.yield vs bond.yields

### ISSUE THREAD

**Issue by auenbauer** [jrvarma/jrvFinance#1]
thx for providing your usefull package (I am using it for bond yield calculations)

a) there are two functions bond.yield and bond.yields and I am trying to understand if there are any differences between them?

b) Is there a way how I could insert a redemption price other than 100 to one of the functions (many bonds have call schedules with redemptions prices other than par and I could use your function to calculate the yield to call if there was an option to insert the redemption price)....

br

**Comment by jrvarma** [comment]
a) bond.yield is for finding ytm of one bond while bond.yields is for computing ytms of a lot of bonds at one shot (by using a vector of values for each input). Actually, bond.yields is just a mapply wrapper around bond.yield.

b) This is a functionality that I should add, but is not there right now. An ugly workaround is as follows. Consider a bond with 5% coupon (payable semi-annually) callable at 102 on 1-Jan-2023 trading at 101 on 1-Jan-2018. To find yield to call, we can do 

> bond.yield('2018-01-01', '2023-01-01', 0.05/1.02, 2, 101/1.02)
0.05126732

I have divided both the coupon and the price by 1.02 since the call is at a premium of 2%. Ugly, but it works. 

I will try and add an optional argument for the redemption value when I get the time.

**Comment by auenbauer** [comment]
Dear Professor Varma!

Thank you very much for providing this elegant idea to work-around this
non-par redemption price problem.

I very much enjoy using your package and will explore the use of the
bond.yields function as I have a very large number of bond yield
calculation to do (1MM+). For now I used mapply on bond.yield and this
worked and the calculation took about 11 minutes for 250k interations. Time
is not very important to me because I will hard code the calculated yields
in a csv and only need to calculate the numbers once but I am curious to
see what the difference of using bond.yields will be and apart from that
using it will most likely make the code shorter and easier.

Thank you very much again!

Best regards,

Günter



2018-01-23 9:55 GMT+01:00 Prof. Jayanth R Varma <notifications@github.com>:

**Comment by andhherson** [comment]
Is it possible to use coupons.dates for a lot of bonds?

**Comment by jrvarma** [comment]
Yield to call is now implemented in Version 1.4.0. The bond functions take an additional parameter `redemption_value` for this purpose.
